### ISSUE TITLE
After starting the fiber node on the Ubuntu system machine, ctrc c fails to exit the node.

### ISSUE THREAD

**Issue by Xcodes-chain** [nervosnetwork/fiber#265]
### Current Behavior

After starting the fiber node on the Ubuntu system machine, ctrc c fails to exit the node.
```
at src/fiber/network.rs:1000
    in ractor::actor::Actor with id: "0.2", name: "Network QmZEoHTja32nxjdMht2HY3hdFBu24wzdovFYnJ1DMuE5Lu"

^C  2024-10-19T12:49:06.574139Z  INFO fnn: Received Ctrl-C, shutting down
    at src/main.rs:234
    in fnn::node with node: ""

^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^Cc^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C
```

### Expected Behavior

Use the ctrc c command to exit the fiber node successfully

### Environment

- **fiber version**: fnn 0.1.0
- **Ckb Chain**: testnet
- **Operating system**: Ubuntu 20.04
- **Arch**: Linux ip-172-31-100-41 6.8.0-1016-aws #17-Ubuntu SMP Mon Sep  2 13:48:07 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- **Installation**: Built from source

### Additional context/Screenshots

[node.log](https://github.com/user-attachments/files/17458747/node.log)

**Comment by contrun** [comment]
The root of this problem is that we rely on ractor to automatically reclaim the resource on exiting. When we receive the exit signal from ctrl+c, we will stop the root actor, and then count on ractor to stop all the children of root actor. We will release all the resources in children actors' `post_stop` function. A recent version of ractor`completely ignore children actors' `post_stop` upon exit. https://github.com/nervosnetwork/fiber/pull/255 this PR upgrade ractor from 0.9.7 to 0.9.8, which makes ctrl-c dysfunctional.

**Comment by chenyukang** [comment]
#255 does not upgraded ractor, it's https://github.com/nervosnetwork/fiber/pull/240 .
