### ISSUE TITLE
[upgrade] Version upgrade issue

### ISSUE THREAD

**Issue by mfuuzy** [nervosnetwork/fiber#270]
Upgrading from an old version to the latest main branch, commit `614affd528d25ddde133bd218bd44482be4d06b6`, resulted in the following exception:
```
thread 'main' panicked at src/store.rs:440:26:
deserialize NodeInfo should be OK: Error("missing field `auto_accept_min_ckb_funding_amount`", line: 1, column: 773)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

After deleting the fiber folder and restarting, it works normally. Is there a way to upgrade without deleting the folder?

**Comment by contrun** [comment]
Unfortunately, we don't have any migration code yet. The problem here is due to the fact we are de-serializing the struct in a very primitive way. Graceful migration is not our current priority, but I think we should have some way to detect breaking changes, and warn the users. See also https://github.com/nervosnetwork/fiber/issues/117
